# Colors (Gruvbox dark)

# Default colors
[colors.primary]
background = '#1d2021'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

[colors.selection]
background = "CellForeground"
text = "CellBackground"

[colors.vi_mode_cursor]
cursor = "CellForeground"
text = "CellBackground"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[font]
size = 16.0

[font.bold]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Bold Oblique"

[font.italic]
family = "DejaVuSansM Nerd Font Mono"
style = "Oblique"

[font.normal]
family = "DejaVuSansM Nerd Font Mono"
style = "Regular"

[window]
# decorations = "none"
dynamic_padding = false
opacity = 1
option_as_alt = "Both"
[scrolling]
history = 100000

[window.padding]
x = 0
y = 0

[mouse]
hide_when_typing = false

[general]
live_config_reload = true
