#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
yabai -m rule --add label="Firfox PIP" app="Firefox" title="^(Picture-in-Picture)$" manage=off
yabai -m rule --add app="FirefoxCP Isolated Web Content" manage=off
yabai -m rule --add app="FirefoxCP WebExtensions" manage=off
yabai -m rule --add app="FirefoxCP Isolated Web Content" manage=off
yabai -m rule --add app="LibreOffice" manage=off
yabai -m rule --add app="ClearVPN" manage=off
yabai -m rule --add app="DBeaver" manage=off

# Closing focused window gives focus to remaining window
yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

# .. more yabai startup stuff

# global settings
# floating windows are always on top (default: off)
# need this for popups to be shown on top of windows
yabai -m config window_topmost off
# yabai -m config mouse_follows_focus on
yabai -m config focus_follows_mouse          autoraise # autofocus
yabai -m config window_placement             first_child
# show shadows only for floating windows
yabai -m config window_shadow                float

yabai -m config window_opacity               on
yabai -m config window_opacity_duration      0.0
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.85

yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize
yabai -m config mouse_drop_action            swap

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  0
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0


echo "yabai configuration loaded.."
