## Lazygit config
gui:
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  theme:
    # lightTheme: false # For terminals with a light background
    selectedLineBgColor:
      - reverse
  skipDiscardChangeWarning: false
  enlargedSideViewLocation: 'top'
  showFileIcons: false
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log -p --color-words --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --syntax-theme gruvbox-dark --paging=never
