## Lazygit config
gui:
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  theme:
    # lightTheme: false # For terminals with a light background
    selectedLineBgColor:
      - reverse
  skipDiscardChangeWarning: false
  enlargedSideViewLocation: 'top'
  showFileIcons: false
  branchColors:
    bugfix: "#fe8019"
    hotfix: "#cc241d"
    feature: "#98971a"
git:
  branchLogCmd: "git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --"
  allBranchesLogCmd: "git log -p --color-words --graph --all --color=always --abbrev-commit --decorate --date=relative  --pretty=medium"
  parseEmoji: true
  paging:
    colorArg: always
    pager: delta --dark --syntax-theme gruvbox-dark --paging=never
  overrideGpg: true
services:
  depot-ssh.1tech.dev: gitlab:depot.1tech.dev
# INFO: this is for mac fix
# os:
#   # workarond for not escaping `/` properly
#   # https://github.com/jesseduffield/lazygit/issues/3064
#   openLink: open -n "$(echo {{link}} | sed 's/%2F/\//g')"
