k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /home/taras/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  noExitOnCtrlC: false
  readOnly: true
  ui:
    enableMouse: true
    headless: false
    logoless: true
    crumbsless: false
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
    # skin: gruvbox_dark_hard
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 500
    buffer: 69420
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
